### ISSUE TITLE
Panic: runtime error: index out of range

### ISSUE THREAD

**Issue by francizs** [hawkular/hawkular-openshift-agent#116] opened 2017-01-30 17:19 UTC
Hello there I am having trouble with getting metrics from jolokia, I get this error:

`I0130 17:11:06.018932       1 metrics_collector_manager.go:125] START collecting metrics from [ctt/xxxx-xxxxx-xxxximpl-27-ds4vo|https://x.x.x.x:8778/jolokia/] every [1m0s]
panic: runtime error: index out of range

goroutine 32 [running]:
panic(0x121dd60, 0xc420016060)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/hawkular/hawkular-openshift-agent/k8s.K8SEndpoint.GetUrl(0xc4202a3c90, 0x5, 0x13664ab, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/hawkular/hawkular-openshift-agent/k8s/configmap_entry.go:82 +0x26b
github.com/hawkular/hawkular-openshift-agent/k8s.(*NodeEventConsumer).startCollecting(0xc420472420, 0xc420524d20)
	/home/travis/gopath/src/github.com/hawkular/hawkular-openshift-agent/k8s/node_event_consumer.go:169 +0x14f
github.com/hawkular/hawkular-openshift-agent/k8s.(*NodeEventConsumer).consumeNodeEvents(0xc420472420)
	/home/travis/gopath/src/github.com/hawkular/hawkular-openshift-agent/k8s/node_event_consumer.go:118 +0x26d
created by github.com/hawkular/hawkular-openshift-agent/k8s.(*NodeEventConsumer).Start
	/home/travis/gopath/src/github.com/hawkular/hawkular-openshift-agent/k8s/node_event_consumer.go:85 +0x5c5`

I see there is a line in configmap_entry.go:  `if len(e.Path) > 0 && e.Path[0] == '/' {
		leadingSlash = ""
	}`

and as it seems e.Path[0] gives this error but nothing more is clear.

**Comment by jmazzitelli** [comment] 2017-01-30 17:23
See the issue I just created on this - #115 - this should be fixed now in master and the latest docker hub image once it gets published (should be soon).

The workaround - set your path. I assume your path is empty in your config map endpoints entry (correct?). If you DO have a path set and it is not an empty string, let me know, that would mean the problem is something else.

But I assume your path is not set. Set it to "/" and it should work.

**Comment by francizs** [comment] 2017-01-30 17:31
@jmazzitelli hello there I just saw your issue and my configmap entry on pod:

  hawkular-openshift-agent: "endpoints:\n- type: jolokia\n  collection_interval: 60s\n  protocol: \"https\"\n  tls:\n    skip_certificate_validation: true\n  port: 8778\n  credentials:\n    username: jolokia\n    password: xxxxxxxxxxxxxxxx\n  path: /jolokia/\n  metrics:\n- name: java.lang:type=Threading#ThreadCount\n  id: the_thread_count\n  type: gauge\n"

I assume by configmap you meant the one on pod and not the one for the agent. As you can see I do have a **path: /jolokia/**.

**Comment by francizs** [comment] 2017-01-30 17:42
@jmazzitelli I added this entry in both pod configmap and also to agents config:

`apiVersion: v1
kind: ConfigMap
metadata:
  name: hawkular-openshift-agent-configuration
  namespace: openshift-infra
  selfLink: /api/v1/namespaces/openshift-infra/configmaps/hawkular-openshift-agent-configuration
  uid: c32f874d-c5ec-11e6-861a-06e4a0f7f911
  resourceVersion: '11756750'
  creationTimestamp: '2016-12-19T13:12:15Z'
  labels:
    metrics-infra: agent
data:
  config.yaml: "collector:\n  minimum_collection_interval_secs: 10\n  metric_id_prefix: pod/${POD:uid}/custom/\n  tags:\n    metric_name: ${METRIC:name}\n    description: ${METRIC:description}\n    units: ${METRIC:units}\n    namespace_id: ${POD:namespace_uid}\n    namespace_name: ${POD:namespace_name}\n    node_name: ${POD:node_name}\n    pod_id: ${POD:uid}\n    pod_ip: ${POD:ip}\n    pod_name: ${POD:name}\n    pod_namespace: ${POD:namespace_name}\n    hostname: ${POD:hostname}\n    host_ip: ${POD:host_ip}\n    labels: ${POD:labels}\n    type: pod\n    collector: hawkular_openshift_agent\n    custom_metric: true\n    path: /jolokia/\n"
  hawkular-openshift-agent: "endpoints:\n- type: jolokia\n  collection_interval: 60s\n  protocol: \"https\"\n  tls:\n    skip_certificate_validation: true\n  port: 8778\n  credentials:\n    username: jolokia\n    password: xxxxxxxxxxxxxxxxxxx\n  path: /jolokia/\n  metrics:\n- name: java.lang:type=Threading#ThreadCount\n  id: the_thread_count\n  type: gauge\n"
`

**Comment by jmazzitelli** [comment] 2017-01-30 18:22
Ok, I'm confused then.  First, if you are running the agent inside OpenShift, then you should not have an "endpoints" section in your agent's own configmap - that is for when running the agent outside of OpenShift, and the endpoint has a different schema. It doesn't have path, it has a full "url" because there is no pod associated with the endpoint and thus you have to give the full URL including the host. The reason you give "protocol", "port", and "path" in the monitored pod's configmap is because the agent uses the host IP assigned to that pod (so you don't provide it).

So perhaps we should step back and let me ask what you are doing.

So, first thing is first - it sounds like you are running the agent in OpenShift. If so, do NOT put any "endpoints" section in your agent's own configuration configmap. Second, the pod with your jolokia endpoint needs to have a configmap associated with it (via a volume description - see the README for details). What does this configmap look like? See the jolokia example for what one should look like - see here: https://github.com/hawkular/hawkular-openshift-agent/blob/master/examples/jolokia-wildfly-example/jolokia-wildfly.yaml#L61-L85  

The jolokia example pod defines this in a volume as you see here: https://github.com/hawkular/hawkular-openshift-agent/blob/master/examples/jolokia-wildfly-example/jolokia-wildfly.yaml#L57-L60

If you'd prefer, we can do this discussion on the [hawkular-dev mailing list ](https://lists.jboss.org/mailman/listinfo/hawkular-dev) for others to participate, but we can have this discussion here if you'd like.

**Comment by francizs** [comment] 2017-01-31 09:24
@jmazzitelli hello again, so I previously didn't have that endpoint entry in hawkular-openshift-agent-configuration, I just added it test if that helps. I have attached **hawkular-openshift-agent-configuration**, **configMap for the pod** and spec section to **DeploymentConfig of an application on pod**.
[hawkular-openshift-agent-configuration.txt](https://github.com/hawkular/hawkular-openshift-agent/files/741507/hawkular-openshift-agent-configuration.txt)
[spec.txt](https://github.com/hawkular/hawkular-openshift-agent/files/741508/spec.txt)
[configMap.txt](https://github.com/hawkular/hawkular-openshift-agent/files/741509/configMap.txt)

So I get the beforementioned error with these configs.

**Comment by francizs** [comment] 2017-01-31 09:55
Here is the full log on agent - 
[full_log.txt](https://github.com/hawkular/hawkular-openshift-agent/files/741596/full_log.txt).

**Comment by jmazzitelli** [comment] 2017-01-31 14:09
@francizs  I noticed the embedded yaml in the config map's data fields are all "serialized" in a single quoted string with \n to denote newlines. OpenShift (at least the version I have) support directly putting in yaml so it is easier to read such as you see here: https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L10

```
data:
  config.yaml: |
    collector:
      minimum_collection_interval_secs: 10
      metric_id_prefix: pod/${POD:uid}/custom/
...
```

I mention this mainly because its more difficult for me to look at your config :) but then I wondered what version of OpenShift you are using. Curious if its an older version.

**Comment by jmazzitelli** [comment] 2017-01-31 14:20
@francizs well, the stack trace in the panic makes it pretty clear it thinks the path is still empty. So I have to assume the config map yaml it is getting isn't correct or the yaml is not correct (perhaps the "path" element is indented incorrectly?). Can you do this - in your agent pod config (where you define the agent startup command) pass in "-v 5" instead of "-v 4". ([see here](https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent.yaml#L85-L86) for an example where this is) This turns on a noisy trace mode and should dump out more details. Maybe that will help see what is going on under the covers in the agent.

**Comment by francizs** [comment] 2017-01-31 15:06
@jmazzitelli thank you for all the support! I got it to work but unfortunately I am not sure what exactly changed. I just re-added the agent the same way as before to a new environment of OpenShift 3.3 and it started to work.

BTW the old env was also OpenShift 3.3 and for some reason whenever I add and save a well formatted .yaml file into whatever config, it gets automatically converted to "serialized" format with \n.

**Comment by jmazzitelli** [comment] 2017-01-31 16:29
OK, glad it is working. I'll close this issue.

**Closed by jmazzitelli** 2017-01-31 16:29 UTC
