### ISSUE TITLE
is there a way to specify the hawkular tenant to be used on openshift ?

### ISSUE THREAD

**Issue by ljuaneda** [hawkular/hawkular-openshift-agent#73] opened 2016-12-23 21:44 UTC
hi,

the hawkular tenant match the pod_namespace on openshift. that's not very convenient when you use hawkular as a datasource in grafana.

I'd like to be able to specify my own tenant as a global config for all metrics of all pods across several namespace.

regard,

ludovic

**Comment by jmazzitelli** [comment] 2016-12-23 22:20
Today this is fixed - the tenant is hardcoded to the pod namespace as you see here:

https://github.com/hawkular/hawkular-openshift-agent/blob/master/k8s/node_event_consumer.go#L170-L175

Originally, the code was configurable but it was thought that having the tenant to be the same as the pod namespace is the way people want it to be (this is how, for example, metrics are stored by heapster) so we removed that feature. But it should be easy to put it back - see this commit:

https://github.com/hawkular/hawkular-openshift-agent/commit/0c7d0e5e469437e22632964ae30284a9505ec693

We could allow a "tenant" to be specifiable in the endpoint definition - if not defined, it would default to what it is today (the namespace). If defined, it would override that default and set it to what you want.

```
endpoints:
- type: jolokia
  port: 8080
. . . 
  tenant: my-endpoint-tenant
```
This however would require you to define your custom tenant across all endpoints. Not what you asked for (you want the global tenant ID defined in the agent config to be used for all pods) but it is a way to set your own tenant ID and you can just make them all the same.

**Comment by jmazzitelli** [comment] 2016-12-23 22:22
@mwringe what are your thoughts?

**Comment by ljuaneda** [comment] 2016-12-24 09:55
It would be fine, maybe even better in the collector statement, in the agent configmap

> this is how, for example, metrics are stored by heapster

My undestanding is that heapster do that using is own namespace_name as the tenant. So the whole metrics are stored with the heapster tenant.

**Comment by jmazzitelli** [comment] 2016-12-24 15:09
With heapster, all metrics within an OpenShift project (aka namespace) are stored with a tenant that is the same name as that namespace. So if you have pods A and B on namespace X, the tenant for all metrics from pods A and B will be "X" and if you have pods C and D on namespace Y, the tenant for all metrics from pods C and D will be "Y". This is currently how the hawkular openshift agent stores its metrics as we tried to mimic as close as possible to how heapster does things.

I'll look to see if we can have this configurable.

**Comment by ljuaneda** [comment] 2016-12-24 15:45
That's strange, I'm pretty to sure to gather all metrics with
"openshift-infra" tenant for all pods and all namespaces.
Le sam. 24 déc. 2016 à 16:09, John Mazzitelli <notifications@github.com> a
écrit :

**Comment by jmazzitelli** [comment] 2016-12-24 16:06
I will defer to @mwringe for more details. But from what I remember the things he told me, that is how heapster stores the data - one tenant per namespace.

**Comment by jmazzitelli** [comment] 2016-12-25 02:57
I implemented this feature in PR #74 - feel free to build this and try it.

The agent configuration can now be told what Tenant to use for all openshift metrics - you do it in the agent configuration's Kubernetes section:

```
kubernetes:
  tenant: your_tenant_here
```

You can set this to be any valid tenant value, and may also include ${var} tokens. The hawkular team will produce its agent docker image with this value set to "${POD:namespace_name}" which will essentially mean no change to how the agent works today - all pod metrics will be stored in a tenant that is the same as the pod namespace. So the agent behavior won't change but it will give users (such as this issue's reporter) the ability to change this if they so choose by simply changing the agent's configuration.

NOTE: this does NOT affect the pod configmap configurations. Only the admin user who deploys and configures the agent can change the tenant value (so you won't see any "tenant" setting in the pod configmap configuration - this is only in the agent's main config).

**Comment by ljuaneda** [comment] 2016-12-25 20:02
Looks perfect, I'll test it this soon I'm back to work on january.

**Comment by jmazzitelli** [comment] 2016-12-30 10:13
I just ran some testing and it works here. I will merge this PR because it does allow us to reconfigure this in the future if need be. But the default configuration remains the same - each will get its own tenant which is the same as the namespace.

This follows the pattern we already have where, rather than hardcode tags, the agent main configuration configures default tags to match that of the current way heapster works - this is no different (the agent main config configures the tenant to be the same as the way heapster works). So now tenant is controlled by configuration and not hardcoded and fixed (so it adds flexibility for different users and for us in the future).

**Comment by ljuaneda** [comment] 2017-01-03 09:55
Hi,

Probably not related but I got errors when I try to build the project :

```
[root@syy09944:hawkular-openshift-agent]# pwd
/root/hawkular-openshift-agent
[root@syy09944:hawkular-openshift-agent]# git pull
remote: Counting objects: 11, done.
remote: Total 11 (delta 8), reused 8 (delta 8), pack-reused 3
Unpacking objects: 100% (11/11), done.
From https://github.com/hawkular/hawkular-openshift-agent
   d4cabe2..7c4327c  master     -> origin/master
Updating d4cabe2..7c4327c
Fast-forward
 README.adoc                                              |  9 +++++++++
 config/config.go                                         |  8 ++++++++
 config/config_test.go                                    | 12 ++++++++++++
 deploy/openshift/hawkular-openshift-agent-configmap.yaml |  2 ++
 k8s/node_event_consumer.go                               | 43 +++++++++++++++++++++++++------------------
 5 files changed, 56 insertions(+), 18 deletions(-)
[root@syy09944:hawkular-openshift-agent]# git log --oneline | head -n 1
7c4327c issue #73: allow agent configuration to say what the tenant is for pod endpoints (#74)
[root@syy09944:hawkular-openshift-agent]# cd ${GOPATH}/src/github.com/hawkular/hawkular-openshift-agent
[root@syy09944:hawkular-openshift-agent]# make build
Cleaning...
Building...
GOOS=linux GOARCH=amd64 CGO_ENABLED=0  go build \
   -ldflags "-X main.version=0.1.0 -X main.commitHash=d4cabe2f13243c16b286402eca19ea371efeea55"
# github.com/hawkular/hawkular-openshift-agent/http
http/http_client.go:46: unknown http.Transport field 'IdleConnTimeout' in struct literal
make: *** [build] Error 2
```

Seems like a golang depedency error. Any idea how to solve this ?

```
[root@syy09944:hawkular-openshift-agent]# go version
go version go1.6.3 linux/amd64
[root@syy09944:hawkular-openshift-agent]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@syy09944:hawkular-openshift-agent]# uname -r
3.10.0-514.el7.x86_64
```

**Comment by jmazzitelli** [comment] 2017-01-03 13:39
Builds fine for me, and travis has not seen this error either. So I assume you do not have your dependencies up to date via Glide. So make sure you tell Glide to update your deps:

```
$ make update_deps
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching updates for k8s.io/client-go.
[INFO]	--> Fetching updates for github.com/golang/protobuf.
[INFO]	--> Fetching updates for github.com/prometheus/client_model.
[INFO]	--> Fetching updates for github.com/hawkular/hawkular-client-go.
[INFO]	--> Fetching updates for github.com/golang/glog.
...and the rest...
```

**Comment by ljuaneda** [comment] 2017-01-04 10:45
I've updated the dependencies and it's changed nothing.
I'm only able to build successfully when commenting out l46 in http/http_client.go
It might be related to golang 1.6 that ships in the rhel7-server-optionnal-rpms channel.

**Comment by jmazzitelli** [comment] 2017-01-04 13:17
It is valid and compiles on go playground as you see here: https://play.golang.org/p/AuVm-kx5uS

I confirmed that IdleConnTimeout was added in 1.7 - see the commit here: https://github.com/golang/go/commit/abc1472d78c70888473634497b49b1c2e1bb6569

So to build, you must use Go 1.7.

**Comment by mwringe** [comment] 2017-01-04 15:23
Under no circumstances should a pod be able to specify under which tenant metrics should be set to.

If we want to have it configurable at the agent level (eg only an admin can change this behaviour). Then I have no problems with this. But the default behaviour should always be to write to the tenant with the same project id.

> That's strange, I'm pretty to sure to gather all metrics with
> "openshift-infra" tenant for all pods and all namespaces.

Metrics are separated by tenant/project, you should not be able to access all metrics using the 'openshift-infra' tenant.

**Comment by jmazzitelli** [comment] 2017-01-04 16:11
> If we want to have it configurable at the agent level (eg only an admin can change this behaviour). Then I have no problems with this. But the default behaviour should always be to write to the tenant with the same project id.

Yes, that is exactly how it works now.

**Comment by jmazzitelli** [comment] 2017-01-05 20:32
the PR has been merged, this feature is now in master.

**Closed by jmazzitelli** 2017-01-05 20:32 UTC
